services:
  eventfinder_backend_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventfinder_backend
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      DATABASE_URL: sqlite+aiosqlite:///database/test_db.sqlite
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@test.test
      LOG_LEVEL: debug
      DOCKER_CONTAINER: "true"
    entrypoint: ["/app/scripts/entrypoint.sh"]
    command: /app/scripts/start.sh
    restart: unless-stopped
